# Generated by Django 3.0.6 on 2020-05-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='selection',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
