# Generated by Django 3.0.6 on 2020-05-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_form_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='choice',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
