# Generated by Django 3.0.6 on 2020-05-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_form_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='choice',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
