# Generated by Django 3.0.6 on 2020-05-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200524_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='choice',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
